# only run for: merge commits, releases and pull-requests
if: type != push OR branch = master OR branch =~ /^\d+\.\d+(\.\d+)?(-\S*)?$/

os: osx
language: swift
osx_image: xcode10.2
xcode_scheme: Workbench
xcode_project: Workbench.xcodeproj
xcode_destination: platform=macOS
